version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  php-apache:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src/html:/var/www/html
    links:
      - db

  drawer:
    container_name: Drawer
    image: php:7.2-apache
    ports:
      - 8000:80
    volumes:
      - ./drawer:/var/www/html

  console:
    container_name: Console
    image: php:7.2-apache
    ports:
      - 8002:80
    volumes:
      - ./console:/var/www/html
  sort:
    container_name: Sort
    image: php:7.2-apache
    ports:
      - 8001:80
    volumes:
      - ./sort:/var/www/html
volumes:
  db_volume:

